INSERT INTO KEYWORD
VALUES (1, 'cars');

INSERT INTO KEYWORD
VALUES (2, 'computers');

INSERT INTO KEYWORD
VALUES (3, 'fitness');

INSERT INTO KEYWORD
VALUES (4, 'gym');

INSERT INTO KEYWORD
VALUES (5, 'ios');

INSERT INTO KEYWORD
VALUES (6, 'programming');

INSERT INTO AUTHOR
VALUES (1, 'Kathy Sierra');

INSERT INTO AUTHOR
VALUES (2, 'Michael Jordan')

